export default {
  index: 'Docs Home',
  'suvishal-operations-analyst-prep': 'Suvishal Operations Analyst Prep',
  'aryan-bigcommerce-prep': 'Aryan Agrawal BigCommerce Prep',
  'qualcomm-prep-material': { display: 'hidden' },
  'natera-ai-solutions-prep': { display: 'hidden' },
  'sirisha-genai-prep': { display: 'hidden' },
  'sirisha-genai-new-prep': { display: 'hidden' },
  'dineesha-support-prep': { display: 'hidden' },
  'dhwani-vora-uline-prep': { display: 'hidden' },
  'manohar-bi-prep': { display: 'hidden' },
  'pratik-hanchate-amplitude-prep': { display: 'hidden' },
  'prathyush-zed-prep': { display: 'hidden' },
  'sai-sharath-finance-ai': { display: 'hidden' },
  'sai-sharath-infosys-stg': { display: 'hidden' },
  'logeswaran-infosys-prep': { display: 'hidden' },
  'janaki-oracle-prep': { display: 'hidden' },
  'ali-shan-integra-prep': { display: 'hidden' },
  'sai-mallesh-aws-prep': { display: 'hidden' },
  'sai-charan-caterpillar-prep': { display: 'hidden' },
  'venkata-chaitanya-aws-glue-prep': { display: 'hidden' },
  'venkata-chaitanya-citi-prep': { display: 'hidden' },
  'haritha-anand-bcg-prep': { display: 'hidden' },
  'torc-prep-guide': { display: 'hidden' },
  'vaishnavi-torc-mcu-applications-prep': { display: 'hidden' },
  'harnish-frontend-backend-coding-prep': { display: 'hidden' },
  'goldman-sachs-behavioral-prep': { display: 'hidden' },
  'amazon-behavioral-prep': { display: 'hidden' },
  'This  is my Resume __Harnish Savadia_(+1) 669-223-': { display: 'hidden' },
  'archived': { display: 'hidden' }
}
