export default {
  index: 'Docs Home',
  'janaki-qa-automation-14day-prep': 'Janaki Ashok Kumar QA Automation Prep',
  'ashutosh-mercor-applied-ai-prep': 'Ashutosh Rudraksh Mercor Applied AI Prep',
  'pavan-fal-senior-data-engineer-prep': 'Pavan Chandramouleswara fal.ai Data Engineer Prep',
  'lawrence-cybersecurity-analyst-prep': 'Lawrence Doh Cybersecurity Analyst Prep',
  'ashish-fedex-data-scientist-prep': 'Sai Ashish Chavali FedEx Data Scientist Prep',
  'charan-amazon-sysde-prep': 'Charan Kumar Amazon SysDE Prep',
  'pranavi-rooms-to-go-prep': 'Pranavi Myneni Rooms To Go Prep',
  'ashutosh-oscar-health-prep': 'Ashutosh Rudraksh Oscar Health Prep',
  'suvishal-operations-analyst-prep': 'Suvishal Operations Analyst Prep',
  'aryan-bigcommerce-prep': 'Aryan Agrawal BigCommerce Prep',
  'dhwani-eq-bank-prep': 'Dhwani Vora EQ Bank Prep',
  'sampath-cid-prep': 'Sampath Thota CID Data Analyst Prep',
  'vijaya-fintech-ops-prep': 'Vijaya Krishna Ande FinTech Ops Prep',
  'qualcomm-prep-material': { display: 'hidden' },
  'natera-ai-solutions-prep': { display: 'hidden' },
  'sirisha-genai-prep': { display: 'hidden' },
  'sirisha-genai-new-prep': { display: 'hidden' },
  'dineesha-support-prep': { display: 'hidden' },
  'dhwani-vora-uline-prep': { display: 'hidden' },
  'manohar-bi-prep': { display: 'hidden' },
  'pratik-hanchate-amplitude-prep': { display: 'hidden' },
  'prathyush-zed-prep': { display: 'hidden' },
  'sai-sharath-finance-ai': { display: 'hidden' },
  'sai-sharath-infosys-stg': { display: 'hidden' },
  'logeswaran-infosys-prep': { display: 'hidden' },
  'janaki-oracle-prep': { display: 'hidden' },
  'ali-shan-integra-prep': { display: 'hidden' },
  'sai-mallesh-aws-prep': { display: 'hidden' },
  'sai-charan-caterpillar-prep': { display: 'hidden' },
  'venkata-chaitanya-aws-glue-prep': { display: 'hidden' },
  'venkata-chaitanya-citi-prep': { display: 'hidden' },
  'haritha-anand-bcg-prep': { display: 'hidden' },
  'torc-prep-guide': { display: 'hidden' },
  'vaishnavi-torc-mcu-applications-prep': { display: 'hidden' },
  'harnish-frontend-backend-coding-prep': { display: 'hidden' },
  'goldman-sachs-behavioral-prep': { display: 'hidden' },
  'amazon-behavioral-prep': { display: 'hidden' },
  'This  is my Resume __Harnish Savadia_(+1) 669-223-': { display: 'hidden' },
  'archived': { display: 'hidden' }
}
