export default {
  index: 'Docs Home',
  'qualcomm-prep-material': 'Qualcomm NPU / Embedded Platform Prep',
  'natera-ai-solutions-prep': 'Natera AI Solutions Prep',
  'sirisha-genai-prep': 'Sirisha GenAI Prep',
  'sirisha-genai-new-prep': 'Sirisha GenAI New Prep',
  'dineesha-support-prep': 'Dineesha Support Prep',
  'manohar-bi-prep': 'Manohar BI Prep',
  'prathyush-zed-prep': 'Prathyush Zed Prep',
  'sai-sharath-finance-ai': 'Sai Sharath Finance AI Prep',
  'sai-sharath-infosys-stg': 'Sai Sharath Infosys STG Prep',
  'logeswaran-infosys-prep': 'Logeswaran Infosys Prep',
  'janaki-oracle-prep': 'Janaki Oracle Prep',
  'ali-shan-integra-prep': 'Ali Shan Integra Prep',
  'sai-mallesh-aws-prep': 'Sai Mallesh AWS Prep',
  'torc-prep-guide': 'Torc Prep Guide (Device Drivers)',
  'vaishnavi-torc-mcu-applications-prep': 'Vaishnavi Torc MCU Applications Prep',
  'harnish-frontend-backend-coding-prep': 'Harnish Frontend + Backend Coding Prep',
  'goldman-sachs-behavioral-prep': 'Goldman Sachs Behavioral Prep',
  'amazon-behavioral-prep': 'Amazon Behavioral Prep',
  'archived': 'Archived Guides'
}
